# Generated by Django 2.2.9 on 2021-01-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pisition',
            new_name='Position',
        ),
    ]
